platform :ios, '13.0'

target 'Example' do
  use_frameworks!
  pod 'HyperionSwift', :path => '../'
  
  # target 'Tests' do
  #   inherit! :search_paths
  #   pod 'HyperionSwift', :path => '../'
  # end
end